DROP TABLE AD_STUDENT_ATTENDANCE;
DROP TABLE AD_STUDENT_COURSE_DETAILS;
DROP TABLE AD_FACULTY_LOGIN_DETAILS;
DROP TABLE AD_FACULTY_COURSE_DETAILS;
DROP TABLE AD_EXAM_RESULTS;
DROP TABLE AD_EXAMS;
DROP TABLE AD_EXAM_TYPES;
DROP TABLE AD_FACULTY;
DROP TABLE AD_STUDENTS;
DROP TABLE AD_PARENT_INFORMATION;
DROP TABLE AD_COURSES;
DROP TABLE AD_ACADEMIC_SESSIONS;
DROP TABLE AD_DEPARTMENTS;



CREATE TABLE AD_ACADEMIC_SESSIONS
(
  ID   		NUMBER,
  NAME 		VARCHAR2(50) NOT NULL
) ;

CREATE TABLE AD_DEPARTMENTS
  (
    ID         		NUMBER ,
    NAME       		VARCHAR2(50) NOT NULL,
    HEAD       		VARCHAR2(50) NOT NULL
) ;

CREATE TABLE AD_PARENT_INFORMATION
  (
    ID   		NUMBER,
    PARENT1_FN        	VARCHAR2(50) NOT NULL,
    PARENT1_LN 		VARCHAR2(50) NOT NULL,
    PARENT2_FN 		VARCHAR2(50) ,
    PARENT2_LN 		VARCHAR2(50)
  ) ;

CREATE TABLE AD_STUDENTS
  (
     ID            	NUMBER ,
     FIRST_NAME         VARCHAR2(50) NOT NULL ,
     LAST_NAME         	VARCHAR2(50) NOT NULL ,
     REG_YEAR      	DATE NOT NULL,
     EMAIL		VARCHAR2(50) NOT NULL,
     PARENT_ID          NUMBER NOT NULL
  ) ;

CREATE TABLE AD_COURSES
  ( 
    ID       		NUMBER,
    NAME      		VARCHAR2 (50) NOT NULL ,
    SESSION_ID      	NUMBER  NOT NULL ,
    DEPT_ID          	NUMBER ,
    LOGON_ID         	VARCHAR2 (10),
    PASSWORD         	VARCHAR2 (10) ,
    BUILDING		VARCHAR2 (50) ,
    ROOM		VARCHAR2 (20),
    DATE_TIME          	VARCHAR2 (20)
  ) ;


CREATE TABLE AD_FACULTY
  (
    ID        	        NUMBER ,
    FIRST_NAME        	VARCHAR2(50) NOT NULL ,
    LAST_NAME      	VARCHAR2(50) NOT NULL,
    EMAIL          	VARCHAR2(50) NOT NULL,
    SALARY           	NUMBER,
    INSURANCE         	VARCHAR2(20),
    HOURLY_RATE       	NUMBER,
    DEPT_ID           	NUMBER
  ) ;

CREATE TABLE AD_EXAM_TYPES
  (
    TYPE         	VARCHAR2(50) ,
    NAME         	VARCHAR2(50) NOT NULL ,
    DESCRIPTION      	VARCHAR2(50)

  ) ;

CREATE TABLE AD_EXAMS
  (
    ID      		NUMBER ,
    START_DATE   	DATE ,
    EXAM_TYPE    	VARCHAR2(50) NOT NULL ,
    COURSE_ID    	NUMBER  NOT NULL
   ) ;


CREATE TABLE AD_EXAM_RESULTS
  (
     STUDENT_ID        	NUMBER ,
     COURSE_ID         	NUMBER ,
     EXAM_ID           	NUMBER ,
     EXAM_GRADE       	NUMBER NOT NULL   
  ) ;


CREATE TABLE AD_STUDENT_ATTENDANCE
  (
     STUDENT_ID         NUMBER ,
     SESSION_ID		NUMBER ,
     NUM_WORK_DAYS   	NUMBER NOT NULL,
     NUM_DAYS_OFF      	NUMBER NOT NULL,
     EXAM_ELIGIBILITY 	VARCHAR2(20) 
  ) ;



CREATE TABLE AD_STUDENT_COURSE_DETAILS
  (
     STUDENT_ID        	NUMBER ,
     COURSE_ID        	NUMBER ,
     GRADE		VARCHAR2(2)NOT NULL
  ) ;


CREATE TABLE AD_FACULTY_COURSE_DETAILS
  (
     FACULTY_ID         NUMBER ,
     COURSE_ID         	NUMBER ,
     CONTACT_HRS        NUMBER NOT NULL  
  ) ;


CREATE TABLE AD_FACULTY_LOGIN_DETAILS
  (
    FACULTY_ID        	NUMBER ,
    LOGIN_DATE_TIME      TIMESTAMP NOT NULL
  ) ;


ALTER TABLE AD_ACADEMIC_SESSIONS ADD CONSTRAINT AD_ACADEMIC_SESSIONS_PK PRIMARY KEY ( SESSION_ID ) ;

ALTER TABLE AD_ACADEMIC_SESSIONS ADD CONSTRAINT AD_SESSIONS_NAME_UK UNIQUE( SESSION_NAME ) ;

ALTER TABLE AD_COURSES ADD CONSTRAINT AD_COURSES_PK PRIMARY KEY (COURSE_ID) ;

ALTER TABLE AD_COURSES ADD CONSTRAINT AD_COURSES_NAME_UK UNIQUE(COURSE_NAME);

ALTER TABLE AD_DEPARTMENTS ADD CONSTRAINT AD_DEPARTMENTS_PK PRIMARY KEY ( DEPT_ID ) ;

ALTER TABLE AD_DEPARTMENTS ADD CONSTRAINT AD_DEPT_NAME_UK UNIQUE( DEPT_NAME ) ;

ALTER TABLE AD_EXAMS ADD CONSTRAINT AD_EXAMS_PK PRIMARY KEY ( EXAM_ID ) ;

ALTER TABLE AD_EXAM_TYPES ADD CONSTRAINT AD_EXAM_TYPES_PK PRIMARY KEY ( EXAM_TYPE ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULTS_PK PRIMARY KEY ( STUDENT_ID, COURSE_ID, EXAM_ID );

ALTER TABLE AD_FACULTY ADD CONSTRAINT AD_FACULTY_PK PRIMARY KEY ( FACULTY_ID ) ;

ALTER TABLE AD_FACULTY ADD CONSTRAINT AD_FACULTY_EMAIL_UK UNIQUE( FACULTY_EMAIL ) ;

ALTER TABLE AD_PARENT_INFORMATION ADD CONSTRAINT AD_PARENT_INFORMATION_PK PRIMARY KEY ( PARENT_ID ) ;

ALTER TABLE AD_STUDENTS ADD CONSTRAINT AD_STUDENTS_PK PRIMARY KEY ( STUDENT_ID ) ;

ALTER TABLE AD_STUDENTS ADD CONSTRAINT AD_STUDENTS_EMAIL_UK UNIQUE(EMAIL );

ALTER TABLE AD_STUDENT_ATTENDANCE ADD CONSTRAINT AD_STUDENT_ATTENDANCE_PK PRIMARY KEY ( STUDENT_ID, SESSION_ID) ;

ALTER TABLE AD_STUDENT_COURSE_DETAILS ADD CONSTRAINT AD_STUDENT_COURSE_PK PRIMARY KEY ( STUDENT_ID, COURSE_ID );

ALTER TABLE AD_FACULTY_COURSE_DETAILS ADD CONSTRAINT AD_FACULTY_COURSE_PK PRIMARY KEY ( FACULTY_ID, COURSE_ID ) ;

ALTER TABLE AD_FACULTY_LOGIN_DETAILS ADD CONSTRAINT AD_FACULTY_LOGIN_PK PRIMARY KEY ( FACULTY_ID, LOGIN_DATE_TIME );

ALTER TABLE AD_COURSES ADD CONSTRAINT AD_COURSES_FK1 FOREIGN KEY ( SESSION_ID ) REFERENCES AD_ACADEMIC_SESSIONS ( SESSION_ID ) ;

ALTER TABLE AD_COURSES ADD CONSTRAINT AD_COURSES_FK2 FOREIGN KEY ( DEPT_ID ) REFERENCES AD_DEPARTMENTS ( DEPT_ID ) ;

ALTER TABLE AD_EXAMS ADD CONSTRAINT AD_EXAMS_FK1 FOREIGN KEY ( EXAM_TYPE ) REFERENCES AD_EXAM_TYPES ( EXAM_TYPE ) ;

ALTER TABLE AD_EXAMS ADD CONSTRAINT AD_EXAMS_FK2 FOREIGN KEY ( COURSE_ID ) REFERENCES AD_COURSES ( COURSE_ID ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULTS_FK1 FOREIGN KEY ( STUDENT_ID ) REFERENCES AD_STUDENTS ( STUDENT_ID ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULTS_FK2 FOREIGN KEY ( COURSE_ID ) REFERENCES AD_COURSES ( COURSE_ID ) ;

ALTER TABLE AD_EXAM_RESULTS ADD CONSTRAINT AD_EXAM_RESULT_FK3 FOREIGN KEY ( EXAM_ID ) REFERENCES AD_EXAMS ( EXAM_ID ) ;

ALTER TABLE AD_FACULTY ADD CONSTRAINT AD_FACULTY_FK FOREIGN KEY ( DEPT_ID ) REFERENCES AD_DEPARTMENTS ( DEPT_ID ) ;

ALTER TABLE AD_STUDENT_COURSE_DETAILS ADD CONSTRAINT AD_STUDENT_COURSE_FK1 FOREIGN KEY ( STUDENT_ID ) REFERENCES AD_STUDENTS ( STUDENT_ID ) ;

ALTER TABLE AD_STUDENT_COURSE_DETAILS ADD CONSTRAINT AD_STUDENT_COURSE_FK2 FOREIGN KEY ( COURSE_ID ) REFERENCES AD_COURSES ( COURSE_ID ) ;

ALTER TABLE AD_STUDENTS ADD CONSTRAINT AD_STUDENTS_FK FOREIGN KEY ( PARENT_ID ) REFERENCES AD_PARENT_INFORMATION ( PARENT_ID ) ;

ALTER TABLE AD_STUDENT_ATTENDANCE ADD CONSTRAINT AD_STUDENT_ATTENDANCE_FK1 FOREIGN KEY ( STUDENT_ID ) REFERENCES AD_STUDENTS ( STUDENT_ID ) ;

ALTER TABLE AD_STUDENT_ATTENDANCE ADD CONSTRAINT AD_STUDENT_ATTENDANCE_FK2 FOREIGN KEY ( SESSION_ID ) REFERENCES AD_ACADEMIC_SESSIONS ( SESSION_ID ) ;

ALTER TABLE AD_FACULTY_COURSE_DETAILS ADD CONSTRAINT AD_FACULTY_COURSE_FK1 FOREIGN KEY ( FACULTY_ID ) REFERENCES AD_FACULTY ( FACULTY_ID ) ;

ALTER TABLE AD_FACULTY_COURSE_DETAILS ADD CONSTRAINT AD_FACULTY_COURSE_FK2 FOREIGN KEY (  COURSE_ID ) REFERENCES AD_COURSES ( COURSE_ID ) ;

ALTER TABLE AD_FACULTY_LOGIN_DETAILS ADD CONSTRAINT AD_FACULTY_LOGIN_FK FOREIGN KEY ( FACULTY_ID ) REFERENCES AD_FACULTY ( FACULTY_ID ) ;

ALTER TABLE AD_FACULTY_LOGIN_DETAILS MODIFY (LOGIN_DATE_TIME TIMESTAMP DEFAULT SYSDATE);

ALTER TABLE AD_PARENT_INFORMATION READ ONLY;